import type { NextPage } from 'next';
import Head from 'next/head';
import ThemeToggle from '../components/ThemeToggle';
import AddNewLink from '../forms/AddNewLink';
import ProgressingForm from '../forms/ProgressingForm';

const Home: NextPage = () => {
  return (
    <div className="w-full flex items-center justify-center bg-red-50">
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute right-0 top-0 mr-4 mt-4 md:mr-6">
        <ThemeToggle />
      </div>

      <main className="mx-auto h-full w-full flex justify-center items-center flex-col bg-slate-100 dark:bg-gray-800 pt-2 md:pt-4">
        <h1 className="text-center mt-10 text-blue-500 font-bold text-3xl">
          URL Shortener
        </h1>
        <h2 className="dark:text-white text-xl w-full mx-auto text-center mt-5">
          Get your url shortened for{' '}
          <span className="text-purple-500 font-bold">free!</span>
        </h2>

        <ProgressingForm>
          <AddNewLink onSubmit={(data) => console.log(data)} />
        </ProgressingForm>
      </main>
    </div>
  );
};

export default Home;
